name:                haskell-chat-room
version:             0.1.0.0
github:              "your-github-username/haskell-chat-room"
license:             MIT
author:              "Phung Chi Tam & Pham Duy Hoang"
maintainer:          "tamphung.31231024593@st.ueh.edu.vn"
extra-source-files:  ["README.md"]

synopsis:            Ung dung chat room da nguoi dung voi truyen file (Haskell)
category:            Network

library:
  source-dirs: src
  exposed-modules:
    - Database
    - Protocol
    - State
    - ParallelOps
  dependencies:
    - base >= 4.7 && < 5
    - containers
    - stm
    - text
    - bytestring
    - aeson
    - websockets
    - sqlite-simple
    - cryptonite
    - parallel

executables:
  server-exe:
    main: Main.hs
    source-dirs: app/server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-chat-room
      - base
      - scotty
      - warp
      - wai-websockets
      - text
      - bytestring
      - aeson
      - mtl
      - wai-cors
      - stm
      - websockets
      - containers
      - http-types
      - wai
      - sqlite-simple
      - directory
      - parallel
      - wai-extra

tests:
  haskell-chat-room-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         -Wall
    dependencies:
      - haskell-chat-room
      - base
      - HUnit
      - tasty
      - tasty-hunit